language: node_js
node_js: node


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
#    - os: osx
#      osx_image: xcode7.3

cache:
  directories:
    - node_modules
